### ISSUE TITLE
为什么代码是残缺的？

### ISSUE THREAD

**Issue by XinZhang-AI** [Hzfinfdu/Diffusion-BERT#33]
为什么代码是残缺的？

**Comment by XinZhang-AI** [comment]
麻烦您更新一下，给您磕一个！

**Comment by Hzfinfdu** [comment]
Hi, 具体是哪里有问题呢？

**Comment by XinZhang-AI** [comment]
![1729867648382](https://github.com/user-attachments/assets/ca8d23ac-881d-4cd1-9aa6-cbc8d8294a7c)
![1729867681815](https://github.com/user-attachments/assets/1a526450-20ae-48aa-be41-c6f3a924bb2f)
好哥哥救救我，我真的很想搞懂您这篇论文，您的创新点太棒了，将扩散模型的去噪任务与Bert完美的结合了起来，求求您了好哥哥！
像图片上这样，有些函数都没有实现
我的邮箱是researcherzx@gmail.com

**Comment by XinZhang-AI** [comment]
我甚至想V您50来一顿疯狂星期四，可以在邮件中附上您的微信收款码吗？这样耽误了您宝贵的时间我才没有愧意

**Comment by Hzfinfdu** [comment]
图1的linear schedule一般不太常用，如果要复现这个部分可以尝试对着上下两个写一下。sry我不太记得为什么这个东西在utils里消失了。图2一般在prob space算loss，我考虑把这个分支删掉，即只用log_space = False

**Comment by XinZhang-AI** [comment]
谢谢好哥哥，您真是太好了,我将在未来四年的研究生涯中大量引用您的各种论文，请允许我在github上亲切的叫您一声：“义父大人在上，请受小人一拜!”
