### ISSUE TITLE
Reimplemented Diffusion-LM 

### ISSUE THREAD

**Issue by Leo-T-Zang** [Hzfinfdu/Diffusion-BERT#9]
Hi,

Thank you for the amazing work.

As I read your paper and noticed that you had reimplemented Diffusion-LM, do you have any plan to open source your implementation as well?

Thanks.

**Comment by Hzfinfdu** [comment]
Hi, thank you for following our work!

The implementation of Diffusion-LM is available at https://github.com/XiangLi1999/Diffusion-LM. Our re-implementation is based on that with slight modification.

If you have any other problems please feel free to contact with me.

**Comment by zhihanyang2022** [comment]
@Hzfinfdu Thanks for the work! For lm1b, did you use padding for the Diffusion-LM re-implementation as well?
